use chrono::prelude::*;
use serenity::{
    builder::{CreateComponents, CreateEmbed},
    model::{channel::ReactionType, id::UserId, interactions::message_component::ButtonStyle},
    utils::Color,
};

#[inline]
pub fn begin(builder: &mut CreateEmbed) -> &mut CreateEmbed {
    begin_with_color(builder, embed_color())
}

#[inline]
pub fn begin_error(builder: &mut CreateEmbed) -> &mut CreateEmbed {
    begin_with_color(builder, embed_color_error())
}

pub fn begin_with_color(builder: &mut CreateEmbed, color: u32) -> &mut CreateEmbed {
    let time = Utc::now();
    let footer = format!("This embed generated by CalBot at {}", time.to_rfc2822());

    builder
        .color(Color::new(color))
        .footer(|b| b.text(footer))
        .timestamp(&time);
    builder
}

#[must_use]
#[allow(clippy::unreadable_literal)]
pub const fn embed_color() -> u32 {
    0xffd042
}

#[must_use]
#[allow(clippy::unreadable_literal)]
pub const fn embed_color_error() -> u32 {
    0xA9263D
}

pub fn build_cleanup(c: &mut CreateComponents, author_id: UserId) -> &mut CreateComponents {
    c.create_action_row(|r| {
        r.create_button(|b| {
            b.style(ButtonStyle::Danger)
                .label("Clean")
                .emoji(ReactionType::Unicode(String::from("\u{1f5d1}")))
                .custom_id(format!("clean;{}", author_id))
        })
    })
}
